const A=document.getElementById("app"),B=document.getElementById("bar"),N=document.getElementById("num");let n=0;
const S=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const FIG=`<div class=figure><div class=figtitle>実験の3つの葉</div><div class=exp><div class=stem></div><div class=pot></div><div class="leaf a"></div><b class="lab la">あ</b><div class="leaf i"><span class=foil></span></div><b class="lab li">い</b><div class="leaf u"><span class=white></span></div><b class="lab lu">う</b></div><div class=legend><b>あ</b>：緑色で光が当たる葉　／　<b>い</b>：緑色の葉の一部をアルミニウムはくでおおう　／　<b>う</b>：緑色部分と白い部分がある葉</div></div>`;
const Q=[
["📖 要点","光合成を行う場所は？","葉緑体",["葉緑体","気孔","道管","師管"],"葉緑体には葉緑素という緑色の成分が含まれます。"],
["📖 要点","葉緑体に含まれる緑色の成分は？","葉緑素",["葉緑素","でんぷん","糖","酸素"],"場所＝葉緑体、緑色の成分＝葉緑素です。"],
["💧 材料","水は根のどこから吸収される？","根毛",["根毛","気孔","師管","葉緑体"],"水は根毛から吸収されます。"],
["💧 材料","吸収された水が通る管は？","道管",["道管","師管","気孔","根毛"],"水は道管を通ります。"],
["🌬️ 材料","二酸化炭素は主にどこから取り入れる？","気孔",["気孔","根毛","道管","師管"],"主に葉のうら側に多い気孔から取り入れます。"],
["☀️ エネルギー","光合成のエネルギー源は？","光",["光","水","酸素","でんぷん"],"光をエネルギー源にします。"],
["🧠 できるもの","光合成でできる2つを選ぼう",["でんぷん","酸素"],["でんぷん","酸素","水","二酸化炭素"],"でんぷんと酸素ができます。","multi"],
["🔗 運ばれ方","でんぷんは運ばれるとき何に変えられる？","糖",["糖","酸素","水","葉緑素"],"水にとけやすい糖に変えられます。"],
["🔗 運ばれ方","糖が通る管は？","師管",["師管","道管","気孔","根毛"],"糖は師管を通って各部へ運ばれます。"],
["🌬️ 放出","酸素はどこから空気中へ放出される？","気孔",["気孔","根毛","道管","師管"],"酸素は気孔から放出されます。"],
["🌱 利用","光合成でつくられたでんぷんの使われ方をすべて選ぼう",["呼吸のエネルギー源","成長のエネルギー源","発芽などのために貯蔵"],["呼吸のエネルギー源","成長のエネルギー源","発芽などのために貯蔵","気孔だけをつくる材料"],"教材では呼吸・成長・貯蔵が示されています。","multi"],
["🧫 ヨウ素でんぷん反応","ヨウ素液で青紫色になるのは何がある部分？","でんぷん",["でんぷん","酸素","水","二酸化炭素"],"でんぷんがあると青紫色になります。"],
["🧪 実験①","実験前に24時間、光を当てない理由は？","もともと葉にあったでんぷんをなくすため",["もともと葉にあったでんぷんをなくすため","葉緑素をなくすため","気孔を閉じるため","水を吸わせるため"],"実験前からあったでんぷんの影響をなくします。"],
["🧪 実験④","葉をあたためたアルコールにつける理由は？","葉の緑色をぬいて反応を見やすくするため",["葉の緑色をぬいて反応を見やすくするため","でんぷんを糖にするため","光をさえぎるため","二酸化炭素を増やすため"],"緑色を取り除き、ヨウ素液の色の変化を見やすくします。"],
["🧪 図で比較","図の「あ」と「い」を比べると、光合成に何が必要だとわかる？","光",["光","葉緑体","道管","酸素"],"同じ緑色の葉で、光が当たる所と、はくで光をさえぎった所を比べます。","fig"],
["🧪 図で比較","図の「あ」と「う」を比べると、光合成に何が必要だとわかる？","葉緑体（葉緑素のある緑色部分）",["葉緑体（葉緑素のある緑色部分）","光","道管","酸素"],"光が当たる条件で、緑色部分と白い部分を比べます。","fig"],
["🍃 図をタップ","葉「い」で、ヨウ素液をつけると青紫色になる部分をタップしよう",null,null,"光が当たった緑色部分です。アルミニウムはくの部分には光が当たりません。","leafI"],
["🍃 図をタップ","葉「う」で、ヨウ素液をつけると青紫色になる部分をタップしよう",null,null,"光が当たり、葉緑体のある緑色部分です。白い部分は青紫色になりません。","leafU"]
];
function header(){B.style.width=(n/Q.length*100)+"%";N.textContent=(n+1)+" / "+Q.length}
function render(){if(n>=Q.length)return summary();header();let x=Q[n];A.innerHTML=`<div class=tag>${x[0]}</div><div class=q>${x[1]}</div>${x[5]=="fig"?FIG:""}<div id=o class=opts></div><div id=f></div>`;if(x[5]=="multi")return multi(x);if(x[5]=="leafI"||x[5]=="leafU")return leaf(x);S(x[3]).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>answer(b,v==x[2],x);o.appendChild(b)})}
function answer(b,ok,x){document.querySelectorAll(".opt").forEach(z=>z.disabled=true);b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ ここを見直そう"}<br>${x[4]}</div><button id=nx class=next>${ok?"次へ":"もう一度"}</button>`;nx.onclick=()=>{if(ok)n++;render()}}
function multi(x){let set=new Set;S(x[3]).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>{set.has(v)?set.delete(v):set.add(v);b.classList.toggle("on")};o.appendChild(b)});let c=document.createElement("button");c.className="next";c.textContent="答え合わせ";c.onclick=()=>{let ok=set.size==x[2].length&&x[2].every(v=>set.has(v));document.querySelectorAll(".opt").forEach(b=>{if(set.has(b.textContent)&&!x[2].includes(b.textContent))b.classList.add("bad")});f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ 選んだところを見直そう"}<br>${x[4]}</div><button id=nx class=next>${ok?"次へ":"もう一度"}</button>`;nx.onclick=()=>{if(ok)n++;render()}};o.after(c)}
function leaf(x){let I=x[5]=="leafI";o.innerHTML=`<div class=figure><div class=figtitle>${I?"葉「い」：中央をアルミニウムはくでおおう":"葉「う」：緑色部分と白い部分がある"}</div><div class=pickleaf>${I?'<span class=cover></span><button class="pick p1" data-ok="1">光が当たった緑色部分</button><button class="pick p2">はくでおおった部分</button>':'<span class=variegated></span><button class="pick p1" data-ok="1">緑色部分</button><button class="pick p2">白い部分</button>'}</div></div>`;document.querySelectorAll(".pick").forEach(b=>b.onclick=()=>{let ok=b.dataset.ok=="1";b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ そこ！":"⚠️ そこではありません"}<br>${x[4]}</div><button id=nx class=next>${ok?"次へ":"もう一度"}</button>`;nx.onclick=()=>{if(ok)n++;render()}})}
function summary(){B.style.width="100%";N.textContent="まとめ";A.innerHTML=`<div class=tag>📒 まとめノート</div><div class=q>第6章　光合成のしくみ</div><div class=flow>水（根毛 → 道管）＋ 二酸化炭素（気孔）<br>＋ 光のエネルギー<br>↓<br>葉緑体で光合成<br>↓<br>でんぷん ＋ 酸素</div><div class=note><b>【大事な言葉】</b><br>葉緑体・葉緑素・根毛・道管・気孔・光・でんぷん・糖・師管・酸素<br><br><b>【運ばれ方】</b><br>でんぷんは水にとけにくいので糖に変えられ、師管を通って体の各部へ運ばれる。酸素は気孔から空気中へ放出される。<br><br><b>【でんぷんの利用】</b><br>呼吸・成長のエネルギー源として使われ、発芽などのために貯蔵される。<br><br><b>【実験のポイント】</b><br>① 24時間光を当てない → もともとのでんぷんをなくす。<br>② 日光を当てる。<br>③ 葉を熱湯につける。<br>④ あたためたアルコール → 葉の緑色をぬく。<br>⑤ 水で洗い、ヨウ素液 → でんぷんがある部分は青紫色。<br><br><b>【比較】</b><br>「あ」と「い」→ 光が必要。<br>「あ」と「う」→ 葉緑体（葉緑素のある緑色部分）が必要。</div>${FIG}<button class=next onclick="boss()">✏️ 書き写した！　章ボスへ</button>`}
function boss(){const qs=S([["水が通る管は？","道管",["道管","師管","気孔","根毛"]],["糖が通る管は？","師管",["師管","道管","気孔","葉緑体"]],["ヨウ素液で青紫色になる物質は？","でんぷん",["でんぷん","酸素","水","二酸化炭素"]],["「あ」と「い」の比較で確かめるものは？","光",["光","葉緑体","道管","酸素"]],["「あ」と「う」の比較で確かめるものは？","葉緑体",["葉緑体","師管","根毛","酸素"]]]);let k=0;function r(){if(k>=qs.length){A.innerHTML='<div class=tag>🏆 COMPLETE</div><div class=q>第6章クリア！</div><div class=fb>要点・実験・図の読み取りまで確認できました。</div><button class=next onclick="location.reload()">もう一度</button>';return}let x=qs[k];A.innerHTML=`<div class=tag>👑 章ボス ${k+1}/5</div><div class=q>${x[0]}</div><div id=o class=opts></div><div id=f></div>`;S(x[2]).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>{let ok=v==x[1];b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ もう一度"}</div><button id=nx class=next>${ok?"次へ":"やり直す"}</button>`;nx.onclick=()=>{if(ok)k++;r()};};o.appendChild(b)})}r()}render();