
const A=document.getElementById('app'),B=document.getElementById('bar'),C=document.getElementById('counter');
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const FIG=`<div class="figure"><div class="figtitle">実験の図</div><div class="exp"><div class="stem"></div><div class="pot"></div><div class="leaf a"></div><b class="lab la">あ</b><div class="leaf i"><span class="foil"></span></div><b class="lab li">い</b><div class="leaf u"><span class="white"></span></div><b class="lab lu">う</b></div><div class="legend"><b>あ</b>：緑色で光が当たる葉　／　<b>い</b>：緑色の葉の一部をアルミニウムはくでおおう　／　<b>う</b>：緑色部分と白い部分がある葉</div></div>`;
const units=[
{title:"光合成を行う場所",focus:"どこで行われる？ 緑色の成分は？",sent:["光合成は、植物の体の中の葉緑体という部分で行われます。","葉緑体には、葉緑素という緑色の成分が含まれています。"],evidence:0,q:"光合成を行う場所は？",a:"葉緑体",opts:["葉緑体","気孔","道管","師管"],link:"葉緑体には葉緑素が含まれます。"},
{title:"水の取り入れと通り道",focus:"水はどこから入り、何を通る？",sent:["水は根の根毛から吸収されます。","吸収された水は道管を通って運ばれます。"],evidence:1,q:"根毛から吸収された水が通る管は？",a:"道管",opts:["道管","師管","気孔","葉緑体"],link:"水は「根毛 → 道管」とつなげて覚えます。"},
{title:"二酸化炭素の取り入れ",focus:"空気中の二酸化炭素はどこから入る？",sent:["二酸化炭素は、主に葉のうら側に多い気孔から取り入れられます。","光合成には水・二酸化炭素・光が必要です。"],evidence:0,q:"二酸化炭素を取り入れる部分は？",a:"気孔",opts:["気孔","根毛","道管","師管"],link:"気孔は、光合成でできた酸素を空気中へ出す部分でもあります。"},
{title:"光合成に必要なもの",focus:"材料とエネルギー源を分けよう",sent:["光合成には、水と二酸化炭素が必要です。","光は、光合成を行うときのエネルギー源になります。"],evidence:1,q:"光合成のエネルギー源は？",a:"光",opts:["光","水","二酸化炭素","酸素"],link:"水・二酸化炭素は材料、光はエネルギー源です。"},
{title:"光合成でできるもの",focus:"何がつくられる？",sent:["光合成によって、でんぷんと酸素ができます。","酸素は気孔を通って空気中に放出されます。"],evidence:0,q:"光合成でできるものを2つ選ぼう",a:["でんぷん","酸素"],opts:["でんぷん","酸素","水","二酸化炭素"],multi:true,link:"でんぷんは植物に利用され、酸素は気孔から放出されます。"},
{title:"でんぷんの運ばれ方",focus:"水にとけにくいでんぷんはどうする？",sent:["でんぷんは水にとけにくいため、水にとけやすい糖に変えられます。","糖は師管を通って植物の体の各部へ運ばれます。"],evidence:0,q:"糖が体の各部へ運ばれるときに通る管は？",a:"師管",opts:["師管","道管","気孔","根毛"],link:"水＝道管、糖＝師管を区別します。"},
{title:"でんぷんの利用",focus:"つくられたでんぷんは何に使う？",sent:["光合成でつくられたでんぷんは、植物自身の生活や成長に使われます。","また、発芽などのために貯蔵されます。"],evidence:1,q:"でんぷんの利用として教材に示されているものをすべて選ぼう",a:["呼吸のエネルギー源","成長のエネルギー源","発芽などのために貯蔵"],opts:["呼吸のエネルギー源","成長のエネルギー源","発芽などのために貯蔵","気孔から空気中へ放出"],multi:true,link:"教材では「呼吸・成長・貯蔵」の3つに整理されています。"},
{title:"ヨウ素でんぷん反応",focus:"何があると何色になる？",sent:["ヨウ素液はうす茶色の液体です。","でんぷんがあると青紫色を示します。"],evidence:1,q:"ヨウ素液で青紫色になるのは何がある部分？",a:"でんぷん",opts:["でんぷん","酸素","水","二酸化炭素"],link:"この反応を使って、葉のでんぷんができた場所を調べます。"}
];
let stage=0,phase=0;
function reset(){A.innerHTML="";}
function progress(){let total=units.length*4+5;let done=Math.min(stage*4+phase,total);B.style.width=(done/total*100)+"%";C.textContent=`${done+1} / ${total}`}
function render(){reset(); if(stage>=units.length)return experimentIntro();progress();let u=units[stage];
if(phase===0){A.innerHTML=`<div class=tag>📖 読む</div><div class=q>${u.title}</div><div class=focus>読むポイント：${u.focus}</div><div class=read>${u.sent.join("<br>")}</div><button class=next onclick="phase=1;render()">根拠を探す →</button>`}
if(phase===1){A.innerHTML=`<div class=tag>🔎 本文から根拠を探す</div><div class=q>「${u.q.replace("を2つ選ぼう","")}」につながる文をタップしよう</div><div class=read id=txt></div><div id=f></div>`;u.sent.forEach((s,i)=>{let sp=document.createElement("div");sp.className="tapline";sp.textContent=s;sp.onclick=()=>{if(i===u.evidence){sp.classList.add("hit");f.innerHTML=`<div class=fb>⭕ ここが根拠！</div><button class=next onclick="phase=2;render()">整理する →</button>`}else f.innerHTML=`<div class="fb bad">⚠️ もう一度。読むポイントに戻って探そう。</div>`};txt.appendChild(sp)})}
if(phase===2){A.innerHTML=`<div class=tag>🔬 整理する</div><div class=q>${u.title}</div><div class=figure><div class=flow><div class=box>${u.sent[0]}</div><div class=arrow>→</div><div class=box>${u.sent[1]}</div></div></div><button class=next onclick="phase=3;render()">本文を隠して思い出す →</button>`}
if(phase===3){A.innerHTML=`<div class=tag>🧠 本文なしで思い出す</div><div class=q>${u.q}</div><div id=o class=opts></div><div id=f></div>`;if(u.multi)return multi(u);shuffle(u.opts).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>answer(b,v===u.a,u);o.appendChild(b)})}}
function answer(b,ok,u){document.querySelectorAll(".opt").forEach(x=>x.disabled=true);b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ ここを見直そう"}<br>${ok?u.link:"本文の関係をもう一度確認しよう。"}</div><button class=next onclick="${ok?"nextUnit()":"render()"}">${ok?"次へ":"もう一度"}</button>`}
function multi(u){let chosen=new Set;shuffle(u.opts).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>{chosen.has(v)?chosen.delete(v):chosen.add(v);b.classList.toggle("sel")};o.appendChild(b)});let c=document.createElement("button");c.className="next";c.textContent="答え合わせ";c.onclick=()=>{let ok=chosen.size===u.a.length&&u.a.every(v=>chosen.has(v));document.querySelectorAll(".opt").forEach(b=>{if(chosen.has(b.textContent)&&!u.a.includes(b.textContent))b.classList.add("bad")});f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ 選んだところを見直そう"}<br>${ok?u.link:"正しいものだけを選び直そう。"}</div><button class=next onclick="${ok?"nextUnit()":"render()"}">${ok?"次へ":"もう一度"}</button>`};o.after(c)}
function nextUnit(){stage++;phase=0;render()}
function experimentIntro(){B.style.width="82%";C.textContent="実験";A.innerHTML=`<div class=tag>🔬 実験問題</div><div class=q>アサガオの葉で、光合成に必要なものを確かめよう</div>${FIG}<div class=focus>図を見ながら答えます。図は問題と同じ画面に残します。</div><button class=next onclick="expQ(0)">実験問題へ →</button>`}
const exps=[
["実験前に24時間、光を当てないようにする理由は？","もともと葉にあったでんぷんをなくすため",["もともと葉にあったでんぷんをなくすため","葉緑素をなくすため","気孔を閉じるため","水を吸わせるため"],"実験前からあったでんぷんの影響をなくします。"],
["葉をあたためたアルコールにつける理由は？","葉の緑色をぬき、色の変化を見やすくするため",["葉の緑色をぬき、色の変化を見やすくするため","でんぷんを糖にするため","光をさえぎるため","二酸化炭素を増やすため"],"ヨウ素液の反応を見やすくします。"],
["図の「あ」と「い」を比べると、何が光合成に必要だとわかる？","光",["光","葉緑体","道管","酸素"],"同じ緑色の葉で、光が当たる部分と光をさえぎった部分を比べます。"],
["図の「あ」と「う」を比べると、何が光合成に必要だとわかる？","葉緑体（葉緑素のある緑色部分）",["葉緑体（葉緑素のある緑色部分）","光","道管","酸素"],"光が当たる条件で、緑色部分と白い部分を比べます。"] ];
function expQ(k){if(k>=exps.length)return leafQ(0);let x=exps[k];A.innerHTML=`<div class=tag>🔬 実験 ${k+1}/4</div><div class=q>${x[0]}</div>${k>=2?FIG:""}<div id=o class=opts></div><div id=f></div>`;shuffle(x[2]).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>{let ok=v===x[1];b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ もう一度"}<br>${ok?x[3]:"条件の違いを図で確認しよう。"}</div><button class=next onclick="${ok?`expQ(${k+1})`:`expQ(${k})`}">${ok?"次へ":"やり直す"}</button>`};o.appendChild(b)})}
function leafQ(k){let isI=k===0;A.innerHTML=`<div class=tag>🍃 図を直接選ぶ ${k+1}/2</div><div class=q>${isI?"葉「い」":"葉「う」"}で、ヨウ素液をつけると青紫色になる部分をタップしよう</div><div class=figure><div class=pickleaf>${isI?'<span class=cover></span><button class="pick p1" data-ok=1>光が当たった緑色部分</button><button class="pick p2">はくでおおった部分</button>':'<span class=variegated></span><button class="pick p1" data-ok=1>緑色部分</button><button class="pick p2">白い部分</button>'}</div></div><div id=f></div>`;document.querySelectorAll(".pick").forEach(b=>b.onclick=()=>{let ok=b.dataset.ok==="1";b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ そこ！":"⚠️ そこではありません"}<br>${isI?"光が当たった緑色部分にでんぷんができます。":"葉緑体のある緑色部分にでんぷんができます。"}</div><button class=next onclick="${ok?(k===0?"leafQ(1)":"summary()"):`leafQ(${k})`}">${ok?"次へ":"もう一度"}</button>`})}
function summary(){B.style.width="94%";C.textContent="📒 まとめノート";A.innerHTML=`<div class="summary"><div class=tag>📒 まとめノート</div><div class=q>第6章　光合成のしくみ</div><div class=summarybox><h3>【今日のテーマ】</h3>植物は、どこで・何を使って光合成をし、何をつくるのか。<h3>【大事な言葉】</h3>葉緑体／葉緑素／根毛／道管／気孔／光／でんぷん／糖／師管／酸素／ヨウ素液<h3>【関係図】</h3><div class=relation>水：根毛 → 道管<br>二酸化炭素：気孔から取り入れる<br>＋ 光のエネルギー<br>↓<br>葉緑体で光合成<br>↓<br>でんぷん ＋ 酸素<br><br>でんぷん → 糖 → 師管 → 体の各部<br>酸素 → 気孔 → 空気中</div><h3>【これだけは覚える！】</h3><div class=checkrow>① 光合成は葉緑体で行われる。</div><div class=checkrow>② 水・二酸化炭素と光を使い、でんぷん・酸素をつくる。</div><div class=checkrow>③ 水は道管、糖は師管。</div><div class=checkrow>④ ヨウ素液は、でんぷんがあると青紫色。</div><div class=checkrow>⑤ 実験では「あ・い」で光、「あ・う」で葉緑体の必要性を確かめる。</div><div class=checkrow>⑥ でんぷんは呼吸・成長に使われ、発芽などのためにも貯蔵される。</div></div>${FIG}<p class=small>ノートに書き写したら、本文とまとめを隠して章ボスへ。</p><button class=next onclick="boss(0)">✏️ 書き写した！　章ボスへ</button></div>`}
const bossQs=[
["光合成を行う場所は？","葉緑体",["葉緑体","気孔","道管","師管"]],
["水が通る管は？","道管",["道管","師管","気孔","根毛"]],
["糖が通る管は？","師管",["師管","道管","気孔","根毛"]],
["ヨウ素液で青紫色になるのは？","でんぷん",["でんぷん","酸素","水","二酸化炭素"]],
["「あ」と「い」の比較で確かめるのは？","光",["光","葉緑体","道管","酸素"]],
["「あ」と「う」の比較で確かめるのは？","葉緑体",["葉緑体","光","師管","酸素"]]
];
function boss(k){B.style.width=(94+k/bossQs.length*6)+"%";C.textContent=`👑 章ボス ${k+1}/${bossQs.length}`;if(k>=bossQs.length){B.style.width="100%";C.textContent="COMPLETE";A.innerHTML=`<div class=tag>🏆 章クリア</div><div class=q>第6章「光合成のしくみ」クリア！</div><div class=fb>読む → 根拠 → 整理 → 思い出す → 実験図 → まとめノート → 章ボスまで完了しました。</div><button class=next onclick="location.reload()">もう一度</button>`;return}let x=bossQs[k];A.innerHTML=`<div class=tag>👑 章ボス</div><div class=q>${x[0]}</div><div id=o class=opts></div><div id=f></div>`;shuffle(x[2]).forEach(v=>{let b=document.createElement("button");b.className="opt";b.textContent=v;b.onclick=()=>{let ok=v===x[1];b.classList.add(ok?"good":"bad");f.innerHTML=`<div class="fb ${ok?"":"bad"}">${ok?"⭕ 正解":"⚠️ もう一度"}</div><button class=next onclick="boss(${ok?k+1:k})">${ok?"次へ":"やり直す"}</button>`};o.appendChild(b)})}
render();
